### ISSUE TITLE
Can't specify color to each block in i3status-rust

### ISSUE THREAD

**Issue by Lucienya** [cardoe/cargo-ebuild#23]
Recently I installed and configured my i3status-rust to my liking and everything but I couldn't get to specify colors to each of the blocks. I'm already using `alternative_tint` to change the background color of every alternate tabs but I wanted to specify colors according to my liking. So is there a way?

**Comment by cardoe** [comment]
You'll want to report this with that package. This package is just a utility to help generate ebuilds for Rust packages for Gentoo.
