### ISSUE TITLE
unable to generate ebuild for pkgs depending on a git rev and not a crates.io release

### ISSUE THREAD

**Issue by r7l** [cardoe/cargo-ebuild#25]
When trying to build an ebuild for https://github.com/dani-garcia/bitwarden_rs cargo-ebuild failed over packages with versions without an official release. 

What they did is adding a package version with:

`rocket 0.5.0-dev (git+https://github.com/SergioBenitez/Rocket?rev=dbcb0a75b9556763ac3ab708f40c8f8ed75f1a1e)` 

There is no 0.5.0-dev version as this is just a commit.

Would it be possible to allow commits?

**Comment by cardoe** [comment]
I'm not really sure how that would work. We'd have to have the Gentoo Package Manager download the git repo at a specific revision to a special directory, which would make it operate like a -9999 ebuild which does network access outside of `src_fetch`.

**Comment by r7l** [comment]
Even that would be nice. So you could at least have -9999 ebuilds.

**Comment by cardoe** [comment]
This would require support in the `cargo.eclass`, which currently only supports crates that are available from crates.io

**Comment by r7l** [comment]
Ok. Maybe we just close the issue. I might just use a docker container then. It's sad to see things getting more and more complicated to properly install software in Linux when everyone is expecting language based package management systems to be used. But most people probably don't care.
