### ISSUE TITLE
Why `RESTRICT=mirror`?

### ISSUE THREAD

**Issue by lo48576** [cardoe/cargo-ebuild#32]
https://github.com/cardoe/cargo-ebuild/blob/326d33b8b3eb173783820d2d596444a1914b41d8/src/ebuild.template#L18

> The RESTRICT="mirror" setting should be used if we cannot legally mirror certain files; files will still be downloaded from the original locations.
>
> [Mirrors – Gentoo Development Guide](https://devmanual.gentoo.org/general-concepts/mirrors/index.html)

Many projects written in Rust are OSS (as far as I know), and `RESTRICT=mirror` seems not necessary for such usual OSS applications, especially when we want ebuild files for them.

Why is this line included in default template?

If this exists for safety (i.e. to prevent accidentally mirroring proprietary stuff), then I want some comments in the template to indicate when this line is necessary and when unnecessary.

**Comment by lo48576** [comment]
Ok, I understand this exists to prevent portage from fetching crates from mirrors while they are not deployed to mirror servers.
I still want comment lines for this (because actually mirroring is not "restrict"-ed), but `RESTRICT=mirror` itself would be useful and should not be removed for now.

**Comment by cardoe** [comment]
PR is welcome if you'd like to add that boilerplate into every ebuild.

**Comment by cardoe** [comment]
Closing as abandoned.
