### ISSUE TITLE
Feature request: workspace support

### ISSUE THREAD

**Issue by gyakovlev** [cardoe/cargo-ebuild#34]
it'd be great if cargo-ebuild could skip adding crates for packages present in workspace

detailed example here https://github.com/BurntSushi/ripgrep/issues/1602#issuecomment-635818652

build should have used local sources, instead of downloading .crate versions

for instance, for ripgrep-12.1.0 ebuild should not have contained the following lines:

globset-0.4.5
grep-0.2.6
grep-cli-0.1.4
grep-matcher-0.1.4
grep-pcre2-0.1.4
grep-printer-0.1.5
grep-regex-0.1.8
grep-searcher-0.1.7
ignore-0.4.15

because those are workspace members defined in Cargo.toml

https://github.com/BurntSushi/ripgrep/blob/e8822ce97a191d8a5830fd5b77b7ae424cd645b5/Cargo.toml#L31-L42

and I've run in situation where .crate was used instead of workspace member, and workspace member had some functionality that's not part of published .crate yet.

**Comment by epsilon-0** [comment]
OMG thanks a lot, yes, this would be nice!

**Comment by cardoe** [comment]
I’m all for this. We just use the `cargo-metadata` crate which wraps the `cargo metadata` command to give structured data. If you have suggestions on how to detect that from that data I’m game for a change.

**Comment by gyakovlev** [comment]
https://github.com/cardoe/cargo-ebuild/commit/75a2f5b83302b7b747cfb41e75d4d9b2adfff92f looks like it fixed it, so far good. thanks!
