### ISSUE TITLE
Cargo doesn't allow for a recent stable LibreSSL

### ISSUE THREAD

**Issue by routesmith** [cardoe/cargo-ebuild#5]
Apologies if this is not the appropriate place to report this, please feel free to redirect if so.

   Upon trying to build cargo with LibreSSL 2.6.4 (upgrading from LibreSSL 2.6.0 ) on Gentoo, the build errors out with:

> thread 'main' panicked at '
> 
> This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
> 2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
> aborting due to this version mismatch.

   LibreSSL 2.6.0 is a development release, of which LibreSSL 2.6.3 and 2.6.4 are marked as stable.   It would be beneficial to allow the build dependencies for cargo to allow a match of either of these later releases so people can move away from potentially unstable development releases.

  Contrast and compare the release notes:
  [LibreSSL 2.6.0 Release Notes](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.6.0-relnotes.txt)
  [LibreSSL 2.6.3 Release Notes](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.6.3-relnotes.txt)
  [LibreSSL 2.6.4 Release Notes](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.6.4-relnotes.txt)

  I've attached the full log from my attempt to emerge to LibreSSL 2.6.4.

Thanks!
[cargo_build_log_failure_libressl_2.6.4.txt](https://github.com/cardoe/cargo-ebuild/files/1617522/cargo_build_log_failure_libressl_2.6.4.txt)

**Comment by gibix** [comment]
If the bug is still present, please submit a bug report to gentoo's (bugzilla)[https://bugs.gentoo.org/].

**Comment by cardoe** [comment]
@routesmith The proper place would be in https://bugs.gentoo.org/ This repo is for a project that helps generate ebuilds for different crates available at crates.io
